spring:
  application:
     name: feign_client
server:
  port: 9981
feign-data:
  url: "http://localhost:9983"
weather:
  api:
    url: "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
    key:



