apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
          - containerPort: 9002  # 수정된 포트
          env:
            - name: SPRING_R2DBC_URL
              value: "r2dbc:mysql://polar-mysql:3306/order?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8"
            - name: SPRING_R2DBC_USERNAME
              value: "root"
            - name: SPRING_R2DBC_PASSWORD
              value: "1234"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:9001"  # catalog-service URL 추가
            - name: SPRING_RABBITMQ_HOST
              value: "polar-rabbitmq"  # RabbitMQ URL 추가