services:
  edge-service:
    build:
      context: C:\Users\hi-pc-999\Desktop\java_2\polar-service\edge-service
      dockerfile: Dockerfile
    depends_on:
     - polar-mysql
        
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
    environment:
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - AUTH_SERVICE_URL=http://auth-service:9004
    

  catalog-service:
    build:
      context: C:\Users\hi-pc-999\Desktop\java_2\polar-service\catalog-service
      dockerfile: Dockerfile
    depends_on:
      - polar-mysql
        
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://polar-mysql:3306/catalog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    

  order-service:
    build:
      context: C:\Users\hi-pc-999\Desktop\java_2\polar-service\order-service
      dockerfile: Dockerfile
    depends_on:
      - polar-mysql
      - polar-rabbitmq
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://polar-mysql:3306/order?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=1234
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
    
  auth-service:
    build:
      context: C:\Users\hi-pc-999\Desktop\java_2\polar-service\auth-service
      dockerfile: Dockerfile
    depends_on:
      - polar-mysql
        
    image: "auth-service"
    container_name: "auth-service"
    ports:
      - 9004:9004
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://polar-mysql:3306/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      

  polar-mysql:
    image: "mysql:latest"
    container_name: "polar-mysql"
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234   
      - MYSQL_DATABASE=catalog  
      - MYSQL_DATABASE=order
      - MYSQL_DATABASE=auth
      
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
       
    
    

  dispatcher-service:
    build:
      context: C:\Users\hi-pc-999\Desktop\java_2\polar-service\dispatcher-service
      dockerfile: Dockerfile
    image: dispatcher-service:latest
    container_name: dispatcher-service
    ports:
      - "9003:9003"
    environment:
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=1234
    # depends_on:
    #   - polar-rabbitmq
    #   - polar-mysql


  polar-rabbitmq:
    image: "rabbitmq:management"
    container_name: "polar-rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=1234
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
