services:
  

  info-service:
    build:
      context: C:\Users\hi-pc-999\Desktop\java_2\polar-service\info-service
      dockerfile: Dockerfile
    depends_on:
      polar-mysql:
        condition: service_healthy
    image: "info-service"
    container_name: "info-service"
    ports:
      - 9001:9001
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://polar-mysql:3306/info?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    

  

  polar-mysql:
    image: "mysql:latest"
    container_name: "polar-mysql"
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234   
      - MYSQL_DATABASE=info 
      
      
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    
    healthcheck:  # ✅ MySQL이 완전히 실행될 때까지 대기
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10  

