server:
  port: 9004
spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://polar-mysql:3306/auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.authservice.model

jwt:
  issuer: test@gmail.com
  secret_key: O4SxPzNI26ON9JzP9Yx1ffnBKucULNdrUrL0t114BdgRmvKGFGT9RnLp8BP1MG+RosB46Tb6V7WjeSKM/1EN2Q==