server:
  port: 9001
spring:
  application:
    name: info-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://polar-mysql:3306/info?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/info?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234